
export class RouteConstants {
  public static AthletesPage = 'athletes'
  public static AthletesStatePage = 'athletes/state'
  public static AthletesAreaPage = 'athletes/area'
  public static AthletesCityPage = 'athletes/city'
  public static EventsPage = 'events'
  public static EventsStatePage = 'events/state'
  public static EventsAreaPage = 'events/area'
  public static EventsCityPage = 'events/city'
  public static RaceSeriesDashboardPage = 'raceSeriesDashboard'
  public static RaceLeaderboardPage = 'raceLeaderboard'
  public static CourseLeaderboardPage = 'courseLeaderboard'
  public static IndividualResultPage = 'individualResult'
  public static IndividualResultComparePage = 'individualResultCompare'
  public static AthletePage = 'athlete'
  public static AthleteComparePage = 'athleteCompare'
  public static AdvancedSearch = 'advancedSearch'
  public static AwardsPodiumPage = 'awardsPodium'
  public static RacesByMonthReport = 'racesByMonthReport'
  public static AthleteResultsReport = 'athleteResultsReport'
}
